name: Generate Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Changelog
      uses: conventional-changelog-action@v3
      with:
        release-count: 0
        skip-on-empty: true
        version-file: 'VERSION.md'
        output-file: 'CHANGELOG.md'
        git-make-whole-file: true
        preset: 'angular'
        tag-prefix: 'v'
        commit-path: '.'
        release-count: 0
        skip-on-empty: true
        version-file: 'VERSION.md'
        output-file: 'CHANGELOG.md'
        git-make-whole-file: true
        preset: 'angular'
        tag-prefix: 'v'
        commit-path: '.'
