name: Notifications

on:
  workflow_run:
    workflows: ["CI Pipeline", "Deploy to Production Server", "Code Quality Checks"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify Slack on Success
      if: github.event.workflow_run.conclusion == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#deployments'
        text: |
          🎉 *Deployment Successful!*
          
          **Workflow:** ${{ github.event.workflow_run.name }}
          **Branch:** ${{ github.event.workflow_run.head_branch }}
          **Commit:** ${{ github.event.workflow_run.head_commit.message }}
          **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
          **Duration:** ${{ github.event.workflow_run.run_duration_ms }}ms
          
          [View Details](${{ github.event.workflow_run.html_url }})
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Notify Slack on Failure
      if: github.event.workflow_run.conclusion == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#deployments'
        text: |
          ❌ *Deployment Failed!*
          
          **Workflow:** ${{ github.event.workflow_run.name }}
          **Branch:** ${{ github.event.workflow_run.head_branch }}
          **Commit:** ${{ github.event.workflow_run.head_commit.message }}
          **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
          **Duration:** ${{ github.event.workflow_run.run_duration_ms }}ms
          
          [View Details](${{ github.event.workflow_run.html_url }})
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Notify Discord on Success
      if: github.event.workflow_run.conclusion == 'success'
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          🎉 **Deployment Successful!**
          
          **Workflow:** ${{ github.event.workflow_run.name }}
          **Branch:** ${{ github.event.workflow_run.head_branch }}
          **Commit:** ${{ github.event.workflow_run.head_commit.message }}
          **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
          
          [View Details](${{ github.event.workflow_run.html_url }})
    
    - name: Notify Discord on Failure
      if: github.event.workflow_run.conclusion == 'failure'
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ❌ **Deployment Failed!**
          
          **Workflow:** ${{ github.event.workflow_run.name }}
          **Branch:** ${{ github.event.workflow_run.head_branch }}
          **Commit:** ${{ github.event.workflow_run.head_commit.message }}
          **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
          
          [View Details](${{ github.event.workflow_run.html_url }})
