name: Test Notifications

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of notification to test'
        required: true
        default: 'success'
        type: choice
        options:
          - success
          - failure
          - info

jobs:
  test-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Success Notification
      if: github.event.inputs.test_type == 'success'
      run: |
        echo "🎉 Testing Success Notification"
        echo "Workflow: Test Notifications"
        echo "Status: Success"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "Time: $(date)"
        echo "View Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    
    - name: Test Failure Notification
      if: github.event.inputs.test_type == 'failure'
      run: |
        echo "❌ Testing Failure Notification"
        echo "Workflow: Test Notifications"
        echo "Status: Failure"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "Time: $(date)"
        echo "View Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    
    - name: Test Info Notification
      if: github.event.inputs.test_type == 'info'
      run: |
        echo "ℹ️ Testing Info Notification"
        echo "Workflow: Test Notifications"
        echo "Status: Info"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "Time: $(date)"
        echo "View Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    
    - name: Check Notification Settings
      run: |
        echo "📊 Notification Settings:"
        echo "Slack Webhook: ${{ secrets.SLACK_WEBHOOK_URL != '' && 'Configured' || 'Not configured' }}"
        echo "Discord Webhook: ${{ secrets.DISCORD_WEBHOOK != '' && 'Configured' || 'Not configured' }}"
        echo ""
        echo "To configure notifications:"
        echo "1. Go to Settings → Secrets and variables → Actions"
        echo "2. Add SLACK_WEBHOOK_URL and/or DISCORD_WEBHOOK"
        echo "3. Run this workflow again"
